### ISSUE TITLE
Unable to run main.py

### ISSUE THREAD

**Issue by 8osman** [Jerrkawz/GarageQTPi#29]
I've installed everything onto my pi.
But when running main.py I get

```
Welcome to GarageBerryPi!
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    user = CONFIG['mqtt']['user']
TypeError: string indices must be integers, not str
```
I seemed to be getting lots of errors with the config.yaml but have been able to resolve those just by changing the spaces..... however this error could be related. I'm installing via ssh from a windows 10 computer.

**Comment by 8osman** [comment]
Just re-reading the instructions and it says a pi 3 to be used. Think the one I have out there is a pi 2b is that going to make a difference?

**Comment by 8osman** [comment]
I've re-downloaded everything, re-installed everything. I've stripped back the config.yaml to only the mqtt logon details.

I'm still getting the same error. I'm confident now this is a programming issue..... it's just outside of my knowledge base.  :-(

**Comment by 8osman** [comment]
okay fixed the first fault
```
mqtt:
    host: 192.168.0.3
    port: 1883
    user: homeassistant
    password:
```
I hadn't got a space between the 'user:' and the user name. 

however I'm onto problem 2 now.

```
Welcome to GarageBerryPi!
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    if not doorCfg['name']:
TypeError: string indices must be integers, not str
```
Spacing all looks good this time!? Maybe

my doors name id etc from config.yaml

```
doors:
    id: 'left'
    name: 'left Garage Door' #defaults to an unsanitized version of the id paramater
    relay: 23
    state: 17
    state_mode: normally_open #defaults to normally open, uncomment to switch
    invert_relay: false #defaults to false, uncomment to turn relay pin on by default
    state_topic: "home-assistant/cover"
    command_topic: "home-assistant/cover/set"
    id: 'right'
    name: 'right Garage Door' #defaults to an unsanitized version of the id paramater
    relay: 24 
    state: 27 
    state_mode: normally_open #defaults to normally open, uncomment to switch
    invert_relay: false #defaults to false, uncomment to turn relay pin on by default
    state_topic: "homeassistant/cover"
    command_topic: "homeassistant/cover/set"

```

This is being a little tricky...
