### ISSUE TITLE
device_class not set when using discovery

### ISSUE THREAD

**Issue by dyde121** [Jerrkawz/GarageQTPi#41]
When using discovery via MQTT, the garage door is configured as a generic "cover" ie. blinds.
It would be great if the MQTT Cover device_class could be set to "garage"

**Comment by dyde121** [comment]
Workaround applied in Home Assistant
```
homeassistant:
  customize:
    cover.garage_door:
      device_class: garage
```
